### ISSUE TITLE
[Co-Create]: FEATURE TITLE - eDVIR update vehicle list

### ISSUE THREAD

**Issue by SimonKay23** [gerald560/Co-Create#2]
### Is your feature request related to a problem? Please describe.

Not related to a problem, but an enhancement.

### Describe the solution you'd like

Add all non-Class 5-8 vehicles and auto-populate the odometer read when inputting.  It takes unnecessary time for me to input these items.

### Describe alternatives you've considered

N/A

**Comment by gerald560** [comment]
SImon this is good feedback we will prioritize this, will keep you posted on timeline

**Comment by gerald560** [comment]
THis was done in sep
